import React from 'react';

const RegionData = React.createContext([]);
export default RegionData;

export const RegionDataProvider = (props) => {
  // async function connectBackend() {
  //   try {
  //     const provinceCodes = ['ON', 'QC', 'BC', 'MB', 'NT', 'NS', 'NU', 'PE', 'SK', 'YT', 'NB', 'AB', 'NL'];
  //     const provinceDataJson = await Promise.all(provinceCodes.map((code) => fetch(`http://localhost:5000/api/v1/CanadaCovidInfo/${code}/provinceInfo`)));
  //     const provinceData = await Promise.all(provinceDataJson.map((header) => header.json()));

  // //     let newProvinceData = provinceData.reduce(function (map, obj) {
  //       map[obj.prov] = obj;
  //       return map;
  //     }, {});

  //     console.log(newProvinceData);

  //     for (const province in newProvinceData) {
  //       fetch(`http://localhost:5000/api/v1/CanadaCovidInfo/${province}/allRegionsInfo`)
  //         .then(response => response.json())
  //         .then(data => {
  //           console.log(data);
  //           newProvinceData[province].regions = data;
  //         })
  //     }

  //     console.log(newProvinceData);
  //     console.log("Hello!");
  //   } catch (err) {
  //     console.log(err);
  //   }
  //   console.log(provinceData)
  // }

  // connectBackend()

  const regionData = {
    NL: {
      active_cases: 45,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 799586,
      cumulative_cases: 1555,
      cumulative_cvaccine: 377639,
      cumulative_deaths: 7,
      cumulative_dvaccine: 876150,
      cumulative_recovered: 1503,
      cumulative_testing: 286325,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'NL',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'NL',
      new_cases: 45,
      total_cases: 1555,
      total_death: 7,
      fully_vaccinated: 377639,
      regions: [
        {
          prov: 'NL',
          region: 'Eastern',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 1160,
          total_death: 6,
          fully_vaccinated: null,
          active_cases: '',
          population: 317664,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NL',
          region: 'Central',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 171,
          total_death: 0,
          fully_vaccinated: null,
          active_cases: '',
          population: 91201,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NL',
          region: 'Western',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 182,
          total_death: 1,
          fully_vaccinated: null,
          active_cases: '',
          population: 76608,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NL',
          region: 'Labrador-Grenfell',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 38,
          total_death: 0,
          fully_vaccinated: null,
          active_cases: '',
          population: 36069,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    AB: {
      active_cases: 19201,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 5754307,
      cumulative_cases: 277558,
      cumulative_cvaccine: 2699191,
      cumulative_deaths: 2523,
      cumulative_dvaccine: 6897135,
      cumulative_recovered: 255834,
      cumulative_testing: 5333147,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'Alberta',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'AB',
      new_cases: 19201,
      total_cases: 277558,
      total_death: 2523,
      fully_vaccinated: 2699191,
      regions: [
        {
          prov: 'ab',
          region: 'South',
          date: '2021-09-17',
          new_cases: 245,
          new_death: 2,
          total_cases: 17025,
          total_death: 179,
          fully_vaccinated: 171096,
          active_cases: '',
          population: 306399,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.558409133189077,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.44239086681092304,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'ab',
          region: 'Calgary',
          date: '2021-09-17',
          new_cases: 485,
          new_death: 3,
          total_cases: 108052,
          total_death: 749,
          fully_vaccinated: 1118501,
          active_cases: '',
          population: 1680755,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6654753369765374,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3353246630234627,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'ab',
          region: 'Central',
          date: '2021-09-17',
          new_cases: 568,
          new_death: 6,
          total_cases: 26250,
          total_death: 202,
          fully_vaccinated: 234863,
          active_cases: '',
          population: 479601,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.4897049839345623,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.5110950160654377,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'ab',
          region: 'Edmonton',
          date: '2021-09-17',
          new_cases: 454,
          new_death: 2,
          total_cases: 90066,
          total_death: 1144,
          fully_vaccinated: 923519,
          active_cases: '',
          population: 1443597,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6397346350816745,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.3610653649183256,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'ab',
          region: 'North',
          date: '2021-09-17',
          new_cases: 278,
          new_death: 5,
          total_cases: 34080,
          total_death: 231,
          fully_vaccinated: 216119,
          active_cases: '',
          population: 460964,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.46884138457666974,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.5319586154233302,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    NB: {
      active_cases: 371,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 1138881,
      cumulative_cases: 3237,
      cumulative_cvaccine: 539484,
      cumulative_deaths: 48,
      cumulative_dvaccine: 1309695,
      cumulative_recovered: 2818,
      cumulative_testing: 432494,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'New Brunswick',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'NB',
      new_cases: 371,
      total_cases: 3237,
      total_death: 48,
      fully_vaccinated: 539484,
      regions: [
        {
          prov: 'NB',
          region: 'Zone 1 (Moncton area)',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 866,
          total_death: 6,
          fully_vaccinated: null,
          active_cases: '',
          population: 222694,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NB',
          region: 'Zone 2 (Saint John area)',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 343,
          total_death: 8,
          fully_vaccinated: null,
          active_cases: '',
          population: 176280,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NB',
          region: 'Zone 3 (Fredericton area)',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 606,
          total_death: 2,
          fully_vaccinated: null,
          active_cases: '',
          population: 183421,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NB',
          region: 'Zone 4 (Edmundston area)',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 824,
          total_death: 25,
          fully_vaccinated: null,
          active_cases: '',
          population: 48254,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NB',
          region: 'Zone 5 (Campbellton area)',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 287,
          total_death: 4,
          fully_vaccinated: null,
          active_cases: '',
          population: 25199,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NB',
          region: 'Zone 6 (Bathurst area)',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 170,
          total_death: 2,
          fully_vaccinated: null,
          active_cases: '',
          population: 76763,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NB',
          region: 'Zone 7 (Miramichi area)',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 84,
          total_death: 1,
          fully_vaccinated: null,
          active_cases: '',
          population: 44216,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    YT: {
      active_cases: 21,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 65765,
      cumulative_cases: 716,
      cumulative_cvaccine: 32239,
      cumulative_deaths: 9,
      cumulative_dvaccine: 67840,
      cumulative_recovered: 686,
      cumulative_testing: 12232,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'Yukon',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'YT',
      new_cases: 21,
      total_cases: 716,
      total_death: 9,
      fully_vaccinated: 32239,
      regions: [
        {
          prov: 'YT',
          region: 'Yukon',
          date: '2021-09-16',
          new_cases: 1,
          new_death: 0,
          total_cases: 713,
          total_death: 9,
          fully_vaccinated: 32239,
          active_cases: '',
          population: 40854,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7891271356537916,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.21167286434620844,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
      ],
    },
    SK: {
      active_cases: 4330,
      active_cases_change: 96,
      avaccine: 4251,
      cases: 493,
      cumulative_avaccine: 1515564,
      cumulative_cases: 61558,
      cumulative_cvaccine: 715998,
      cumulative_deaths: 637,
      cumulative_dvaccine: 2004075,
      cumulative_recovered: 56591,
      cumulative_testing: 542241,
      cvaccine: 1917,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'Saskatchewan',
      recovered: 397,
      testing: 1428,
      testing_info: 'NULL',
      prov: 'SK',
      new_cases: 4330,
      total_cases: 61558,
      total_death: 637,
      fully_vaccinated: 715998,
      regions: [
        {
          prov: 'SK',
          region: 'Far North',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 7549,
          total_death: 59,
          fully_vaccinated: 21309,
          active_cases: '',
          population: 37811,
          covid_watchdog_scale: '',
          active_cases_per_million: 1401.7084975271746,
          active_cases_per_million_safe: false,
          fully_vaccinated_proportion: 0.5635661579963502,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.43723384200364973,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'SK',
          region: 'North',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 14391,
          total_death: 176,
          fully_vaccinated: 114484,
          active_cases: '',
          population: 196246,
          covid_watchdog_scale: '',
          active_cases_per_million: 871.3553397266696,
          active_cases_per_million_safe: false,
          fully_vaccinated_proportion: 0.5833698521243745,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.4174301478756255,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'SK',
          region: 'Central',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 3900,
          total_death: 25,
          fully_vaccinated: 78554,
          active_cases: '',
          population: 98566,
          covid_watchdog_scale: '',
          active_cases_per_million: 192.76423918998438,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7969685287015806,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.20383147129841933,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'SK',
          region: 'Saskatoon',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 14664,
          total_death: 125,
          fully_vaccinated: 202407,
          active_cases: '',
          population: 380403,
          covid_watchdog_scale: '',
          active_cases_per_million: 289.1670149814802,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.5320857091032405,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.46871429089675953,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'SK',
          region: 'Regina',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 12828,
          total_death: 160,
          fully_vaccinated: 171657,
          active_cases: '',
          population: 304261,
          covid_watchdog_scale: '',
          active_cases_per_million: 213.63237483607824,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.5641768087267182,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.43662319127328186,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'SK',
          region: 'South',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 6853,
          total_death: 85,
          fully_vaccinated: 105272,
          active_cases: '',
          population: 157175,
          covid_watchdog_scale: '',
          active_cases_per_million: 407.1894385239383,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.669775727692063,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.331024272307937,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    PE: {
      active_cases: 37,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 248935,
      cumulative_cases: 270,
      cumulative_cvaccine: 118795,
      cumulative_deaths: 0,
      cumulative_dvaccine: 283325,
      cumulative_recovered: 233,
      cumulative_testing: 189775,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'PEI',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'PE',
      new_cases: 37,
      total_cases: 270,
      total_death: 0,
      fully_vaccinated: 118795,
      regions: [
        {
          prov: 'PE',
          region: 'Prince Edward Island',
          date: '2021-09-16',
          new_cases: 0,
          new_death: null,
          total_cases: 252,
          total_death: 0,
          fully_vaccinated: 118795,
          active_cases: '',
          population: 156947,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7569115688735688,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.24388843112643122,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
      ],
    },
    NU: {
      active_cases: 1,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 45347,
      cumulative_cases: 659,
      cumulative_cvaccine: 21216,
      cumulative_deaths: 4,
      cumulative_dvaccine: 61530,
      cumulative_recovered: 654,
      cumulative_testing: 11127,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'Nunavut',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'NU',
      new_cases: 1,
      total_cases: 659,
      total_death: 4,
      fully_vaccinated: 21216,
      regions: [
        {
          prov: 'NU',
          region: 'Nunavut',
          date: '2021-09-15',
          new_cases: null,
          new_death: null,
          total_cases: 659,
          total_death: 4,
          fully_vaccinated: 21216,
          active_cases: '',
          population: 38780,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.5470861268695204,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.4537138731304797,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    NS: {
      active_cases: 162,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 1480851,
      cumulative_cases: 6312,
      cumulative_cvaccine: 711312,
      cumulative_deaths: 94,
      cumulative_dvaccine: 1661440,
      cumulative_recovered: 6056,
      cumulative_testing: 1168757,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'Nova Scotia',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'NS',
      new_cases: 162,
      total_cases: 6312,
      total_death: 94,
      fully_vaccinated: 711312,
      regions: [
        {
          prov: 'NS',
          region: 'Zone 1 - Western',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 317,
          total_death: 4,
          fully_vaccinated: null,
          active_cases: '',
          population: 199165,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NS',
          region: 'Zone 2 - Northern',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 467,
          total_death: 1,
          fully_vaccinated: null,
          active_cases: '',
          population: 148470,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NS',
          region: 'Zone 3 - Eastern',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 647,
          total_death: 6,
          fully_vaccinated: null,
          active_cases: '',
          population: 162088,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'NS',
          region: 'Zone 4 - Central',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 4863,
          total_death: 83,
          fully_vaccinated: null,
          active_cases: '',
          population: 461672,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 1.0008,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    NT: {
      active_cases: 217,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 68114,
      cumulative_cases: 720,
      cumulative_cvaccine: 32930,
      cumulative_deaths: 0,
      cumulative_dvaccine: 82230,
      cumulative_recovered: 503,
      cumulative_testing: 31297,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'NWT',
      recovered: 0,
      testing: 210,
      testing_info: 'NULL',
      prov: 'NT',
      new_cases: 217,
      total_cases: 720,
      total_death: 0,
      fully_vaccinated: 32930,
      regions: [
        {
          prov: 'NT',
          region: 'NWT',
          date: '2021-09-16',
          new_cases: 202,
          new_death: 0,
          total_cases: 724,
          total_death: 1,
          fully_vaccinated: 32930,
          active_cases: '',
          population: 44826,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7346183018783742,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.26618169812162584,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    MB: {
      active_cases: 629,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 1954209,
      cumulative_cases: 59612,
      cumulative_cvaccine: 946226,
      cumulative_deaths: 1204,
      cumulative_dvaccine: 2435830,
      cumulative_recovered: 57779,
      cumulative_testing: 962409,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'Manitoba',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'MB',
      new_cases: 629,
      total_cases: 59612,
      total_death: 1204,
      fully_vaccinated: 946226,
      regions: [
        {
          prov: 'MB',
          region: 'Winnipeg',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 34515,
          total_death: 813,
          fully_vaccinated: 581661,
          active_cases: '',
          population: 780414,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7453236359163213,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.2554763640836787,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'MB',
          region: 'Prairie Mountain',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 4147,
          total_death: 82,
          fully_vaccinated: 112242,
          active_cases: '',
          population: 171368,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6549764250035013,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.3458235749964988,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'MB',
          region: 'Interlake-Eastern',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 4417,
          total_death: 53,
          fully_vaccinated: 89357,
          active_cases: '',
          population: 133882,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6674310213471565,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.3333689786528436,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'MB',
          region: 'Northern',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 8196,
          total_death: 55,
          fully_vaccinated: 45694,
          active_cases: '',
          population: 75783,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6029584471451381,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.39784155285486195,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'MB',
          region: 'Southern Health',
          date: '2021-09-17',
          new_cases: null,
          new_death: null,
          total_cases: 8251,
          total_death: 200,
          fully_vaccinated: 109036,
          active_cases: '',
          population: 208018,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.5241661779269102,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.47663382207308985,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    ON: {
      prov: 'ON',
      date: '18-09-2021',
      new_cases: 5970,
      active_cases: 5970,
      total_cases: 585598,
      total_death: 9583,
      fully_vaccinated: 10280570,
      active_cases_per_million: 403.657174570166,
      active_cases_per_million_safe: true,
      fully_vaccinated_proportion: 0.6951132058912581,
      fully_vaccinated_proportion_safe: false,
      vulnerable_proportion: 0.3056867941087419,
      vulnerable_proportion_safe: false,
      isSafe: false,
      regions: [
        {
          prov: 'on',
          region: 'Algoma',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 457,
          total_death: 7,
          fully_vaccinated: 80715,
          active_cases: '',
          population: 117036,
          covid_watchdog_scale: '',
          active_cases_per_million: 51.26627704296114,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6896595919204347,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3111404080795653,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Brant',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 3774,
          total_death: 26,
          fully_vaccinated: 102535,
          active_cases: '',
          population: 151034,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6788868731543891,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.32191312684561096,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Durham',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 26675,
          total_death: 382,
          fully_vaccinated: 501567,
          active_cases: '',
          population: 697355,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7192419929591097,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.28155800704089023,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Grey Bruce',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 2300,
          total_death: 14,
          fully_vaccinated: 116100,
          active_cases: '',
          population: 173372,
          covid_watchdog_scale: '',
          active_cases_per_million: 17.303832222042775,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6696583069930554,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3311416930069446,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Haldimand-Norfolk',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 2881,
          total_death: 48,
          fully_vaccinated: 75454,
          active_cases: '',
          population: 119146,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6332902489382775,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.3675097510617226,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'on',
          region: 'Haliburton Kawartha Pineridge',
          date: '2021-09-18',
          new_cases: -93,
          new_death: 0,
          total_cases: 2395,
          total_death: 76,
          fully_vaccinated: 135425,
          active_cases: '',
          population: 189982,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7128306892231896,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.2879693107768105,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Halton',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 19171,
          total_death: 241,
          fully_vaccinated: 442312,
          active_cases: '',
          population: 596363,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7416824987465688,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.25911750125343125,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Hamilton',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 23983,
          total_death: 410,
          fully_vaccinated: 387559,
          active_cases: '',
          population: 574263,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.674880673141052,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3259193268589479,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Hastings Prince Edward',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 1330,
          total_death: 12,
          fully_vaccinated: 113325,
          active_cases: '',
          population: 170793,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6635225097047303,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3372774902952697,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Huron Perth',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 2110,
          total_death: 65,
          fully_vaccinated: 98577,
          active_cases: '',
          population: 144801,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6807756852507925,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.32002431474920756,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Chatham-Kent',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 2286,
          total_death: 17,
          fully_vaccinated: 68835,
          active_cases: '',
          population: 106091,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6488297782092731,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.35197022179072684,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'on',
          region: 'Kingston Frontenac Lennox & Addington',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 1695,
          total_death: 6,
          fully_vaccinated: 151204,
          active_cases: '',
          population: 208613,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7248062201300973,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.27599377986990264,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Lambton',
          date: '2021-09-18',
          new_cases: 12,
          new_death: 0,
          total_cases: 3748,
          total_death: 69,
          fully_vaccinated: 86132,
          active_cases: '',
          population: 132243,
          covid_watchdog_scale: '',
          active_cases_per_million: 90.74204305709944,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.651316137716174,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.349483862283826,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Leeds Grenville and Lanark',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 1862,
          total_death: 60,
          fully_vaccinated: 135895,
          active_cases: '',
          population: 177605,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7651530080797275,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.2356469919202725,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Middlesex-London',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 13759,
          total_death: 237,
          fully_vaccinated: 355990,
          active_cases: '',
          population: 506008,
          covid_watchdog_scale: '',
          active_cases_per_million: 43.47757347709918,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7035264264596607,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.2972735735403393,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Niagara',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 17226,
          total_death: 426,
          fully_vaccinated: 328759,
          active_cases: '',
          population: 479183,
          covid_watchdog_scale: '',
          active_cases_per_million: 75.12787390203742,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.686082352671109,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.31471764732889107,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'North Bay Parry Sound',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 733,
          total_death: 8,
          fully_vaccinated: 88632,
          active_cases: '',
          population: 129642,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6836673300319341,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.31713266996806594,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Northwestern',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 1143,
          total_death: 9,
          fully_vaccinated: 56271,
          active_cases: '',
          population: 81472,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6906790062843676,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3101209937156324,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Ottawa',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 29151,
          total_death: 594,
          fully_vaccinated: 755572,
          active_cases: '',
          population: 1028514,
          covid_watchdog_scale: '',
          active_cases_per_million: 63.19797299793683,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7346249054461096,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.2661750945538904,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Peel',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 115519,
          total_death: 991,
          fully_vaccinated: 1069784,
          active_cases: '',
          population: 1542001,
          covid_watchdog_scale: '',
          active_cases_per_million: 51.2321327936882,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.693763493019784,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.307036506980216,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Peterborough',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 1777,
          total_death: 23,
          fully_vaccinated: 102945,
          active_cases: '',
          population: 147908,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6960069773102199,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.30479302268978015,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Porcupine',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 2193,
          total_death: 31,
          fully_vaccinated: 53678,
          active_cases: '',
          population: 85422,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6283861300367587,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.37241386996324133,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'on',
          region: 'Renfrew',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 787,
          total_death: 10,
          fully_vaccinated: 70886,
          active_cases: '',
          population: 107955,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6566254457875966,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.34417455421240334,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Eastern',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 5051,
          total_death: 112,
          fully_vaccinated: 145381,
          active_cases: '',
          population: 213064,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.682334885292682,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.31846511470731803,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Simcoe Muskoka',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 13299,
          total_death: 257,
          fully_vaccinated: 408860,
          active_cases: '',
          population: 594494,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6877445356891744,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3130554643108257,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Sudbury',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 2380,
          total_death: 31,
          fully_vaccinated: 134751,
          active_cases: '',
          population: 204640,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6584783033620015,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.34232169663799844,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Thunder Bay',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 3387,
          total_death: 64,
          fully_vaccinated: 108763,
          active_cases: '',
          population: 158165,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6876552966838428,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3131447033161572,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Timiskaming',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 211,
          total_death: 2,
          fully_vaccinated: 21842,
          active_cases: '',
          population: 33800,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6462130177514793,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.35458698224852075,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'on',
          region: 'Waterloo',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 19367,
          total_death: 294,
          fully_vaccinated: 415345,
          active_cases: '',
          population: 595465,
          covid_watchdog_scale: '',
          active_cases_per_million: 60.45695380920793,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6975137077745963,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3032862922254037,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Wellington Dufferin Guelph',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 8925,
          total_death: 127,
          fully_vaccinated: 218176,
          active_cases: '',
          population: 308963,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7061557532779006,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.29464424672209943,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Windsor-Essex',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 19201,
          total_death: 448,
          fully_vaccinated: 283927,
          active_cases: '',
          population: 428556,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6625201840599595,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.33827981594004053,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'York',
          date: '2021-09-18',
          new_cases: -100,
          new_death: 0,
          total_cases: 55923,
          total_death: 759,
          fully_vaccinated: 848521,
          active_cases: '',
          population: 1181485,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7181817797094334,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.28261822029056655,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Southwestern',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 4207,
          total_death: 85,
          fully_vaccinated: 142536,
          active_cases: '',
          population: 215401,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6617239474282849,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3390760525717151,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'on',
          region: 'Toronto',
          date: '2021-09-18',
          new_cases: 0,
          new_death: 0,
          total_cases: 177033,
          total_death: 3641,
          fully_vaccinated: 2123965,
          active_cases: '',
          population: 2965712,
          covid_watchdog_scale: '',
          active_cases_per_million: 51.252447978765304,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7161737215211726,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.2846262784788274,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
      ],
    },
    QC: {
      active_cases: 6867,
      active_cases_change: 57,
      avaccine: 25989,
      cases: 821,
      cumulative_avaccine: 12896211,
      cumulative_cases: 402283,
      cumulative_cvaccine: 6206809,
      cumulative_deaths: 11321,
      cumulative_dvaccine: 14045495,
      cumulative_recovered: 384095,
      cumulative_testing: 4560609,
      cvaccine: 15415,
      date: '18-09-2021',
      deaths: 3,
      dvaccine: 0,
      province: 'Quebec',
      recovered: 761,
      testing: 0,
      testing_info: 'NULL',
      prov: 'QC',
      new_cases: 6867,
      total_cases: 402283,
      total_death: 11321,
      fully_vaccinated: 6206809,
      regions: [
        {
          prov: 'qc',
          region: 'Bas-Saint-Laurent',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 4050,
          total_death: 53,
          fully_vaccinated: 149951,
          active_cases: '',
          population: 197322,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7599304689796373,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.24086953102036265,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'qc',
          region: 'Saguenay',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 11156,
          total_death: 271,
          fully_vaccinated: 208157,
          active_cases: '',
          population: 277796,
          covid_watchdog_scale: '',
          active_cases_per_million: 21.59858313294648,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7493160448674567,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.25148395513254335,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Capitale-Nationale',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 33604,
          total_death: 1119,
          fully_vaccinated: 571576,
          active_cases: '',
          population: 750645,
          covid_watchdog_scale: '',
          active_cases_per_million: 22.64719008319512,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7614464893524902,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.23935351064750982,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'qc',
          region: 'Mauricie',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 16476,
          total_death: 563,
          fully_vaccinated: 370037,
          active_cases: '',
          population: 520285,
          covid_watchdog_scale: '',
          active_cases_per_million: 55.738681684076994,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7112198122183034,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.2895801877816966,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Estrie',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 15889,
          total_death: 356,
          fully_vaccinated: 345917,
          active_cases: '',
          population: 489479,
          covid_watchdog_scale: '',
          active_cases_per_million: 106.23540540043598,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7067044755750502,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.2940955244249498,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Montréal',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 141448,
          total_death: 4782,
          fully_vaccinated: 1519438,
          active_cases: '',
          population: 2052910,
          covid_watchdog_scale: '',
          active_cases_per_million: 127.13660121486086,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7401386324777998,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.2606613675222002,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Outaouais',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 13368,
          total_death: 216,
          fully_vaccinated: 274733,
          active_cases: '',
          population: 397193,
          covid_watchdog_scale: '',
          active_cases_per_million: 78.04769973287546,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6916864093778088,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.30911359062219124,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Abitibi-Témiscamingue',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 1218,
          total_death: 9,
          fully_vaccinated: 104827,
          active_cases: '',
          population: 147542,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.710489216629841,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.29031078337015903,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Côte-Nord',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 599,
          total_death: 4,
          fully_vaccinated: 65591,
          active_cases: '',
          population: 90704,
          covid_watchdog_scale: '',
          active_cases_per_million: 11.024872111483507,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7231323866643147,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.27766761333568535,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Nord-du-Québec',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 134,
          total_death: 0,
          fully_vaccinated: 10059,
          active_cases: '',
          population: 13633,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.73784200102692,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.26295799897308003,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Gaspésie-Îles-de-la-Madeleine',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 2122,
          total_death: 47,
          fully_vaccinated: 74345,
          active_cases: '',
          population: 90334,
          covid_watchdog_scale: '',
          active_cases_per_million: 11.07002900347599,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.8230013062634224,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.17779869373657758,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'qc',
          region: 'Chaudière-Appalaches',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 19955,
          total_death: 370,
          fully_vaccinated: 311385,
          active_cases: '',
          population: 428618,
          covid_watchdog_scale: '',
          active_cases_per_million: 151.65018734630837,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7264860551820036,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.2743139448179965,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Laval',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 34901,
          total_death: 926,
          fully_vaccinated: 286338,
          active_cases: '',
          population: 438973,
          covid_watchdog_scale: '',
          active_cases_per_million: 182.24355484278075,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.652290687582152,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.34850931241784805,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Lanaudière',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 25901,
          total_death: 517,
          fully_vaccinated: 349443,
          active_cases: '',
          population: 515448,
          covid_watchdog_scale: '',
          active_cases_per_million: 114.4635346339495,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6779403547981562,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.32285964520184385,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Laurentides',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 23028,
          total_death: 512,
          fully_vaccinated: 437605,
          active_cases: '',
          population: 620264,
          covid_watchdog_scale: '',
          active_cases_per_million: 140.2628558162331,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7055141036719849,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.2952858963280152,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Montérégie',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 55055,
          total_death: 1564,
          fully_vaccinated: 981904,
          active_cases: '',
          population: 1421586,
          covid_watchdog_scale: '',
          active_cases_per_million: 91.44715831472736,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6907102349066465,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.3100897650933535,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Nunavik',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 50,
          total_death: 0,
          fully_vaccinated: 6841,
          active_cases: '',
          population: 14102,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.4851084952489009,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.5156915047510992,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'qc',
          region: 'Terres-Cries-de-la-Baie-James',
          date: '2021-09-18',
          new_cases: null,
          new_death: null,
          total_cases: 142,
          total_death: 4,
          fully_vaccinated: 12300,
          active_cases: '',
          population: 18131,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.6783961171474271,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.322403882852573,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
      ],
    },
    BC: {
      active_cases: 6413,
      active_cases_change: 0,
      avaccine: 0,
      cases: 0,
      cumulative_avaccine: 7675294,
      cumulative_cases: 177954,
      cumulative_cvaccine: 3661611,
      cumulative_deaths: 1888,
      cumulative_dvaccine: 8027560,
      cumulative_recovered: 169653,
      cumulative_testing: 3756252,
      cvaccine: 0,
      date: '18-09-2021',
      deaths: 0,
      dvaccine: 0,
      province: 'BC',
      recovered: 0,
      testing: 0,
      testing_info: 'NULL',
      prov: 'BC',
      new_cases: 6413,
      total_cases: 177954,
      total_death: 1888,
      fully_vaccinated: 3661611,
      regions: [
        {
          prov: 'bc',
          region: 'Fraser',
          date: '2021-09-17',
          new_cases: 239,
          new_death: 2,
          total_cases: 94222,
          total_death: 945,
          fully_vaccinated: 1335526,
          active_cases: '',
          population: 1902586,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.701953026039296,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.29884697396070403,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'bc',
          region: 'Interior',
          date: '2021-09-17',
          new_cases: 183,
          new_death: 5,
          total_cases: 25196,
          total_death: 219,
          fully_vaccinated: 544968,
          active_cases: '',
          population: 805216,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.676797281723165,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.3240027182768351,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'bc',
          region: 'Island',
          date: '2021-09-17',
          new_cases: 102,
          new_death: 0,
          total_cases: 7662,
          total_death: 58,
          fully_vaccinated: 611677,
          active_cases: '',
          population: 846030,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7229968204437195,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.27780317955628053,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
        {
          prov: 'bc',
          region: 'Northern',
          date: '2021-09-17',
          new_cases: 3557,
          new_death: 0,
          total_cases: 10362,
          total_death: 166,
          fully_vaccinated: 157030,
          active_cases: '',
          population: 298068,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.5268260933746662,
          fully_vaccinated_proportion_safe: false,
          vulnerable_proportion: 0.47397390662533384,
          vulnerable_proportion_safe: false,
          isSafe: false,
        },
        {
          prov: 'bc',
          region: 'Vancouver Coastal',
          date: '2021-09-17',
          new_cases: 83,
          new_death: 4,
          total_cases: 40271,
          total_death: 500,
          fully_vaccinated: 937412,
          active_cases: '',
          population: 1219436,
          covid_watchdog_scale: '',
          active_cases_per_million: 0,
          active_cases_per_million_safe: true,
          fully_vaccinated_proportion: 0.7687258699923571,
          fully_vaccinated_proportion_safe: true,
          vulnerable_proportion: 0.23207413000764288,
          vulnerable_proportion_safe: true,
          isSafe: true,
        },
      ],
    },
  };

  return <RegionData.Provider value={regionData}>{props.children}</RegionData.Provider>;
};
